// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWqG7YMAzChV_Agtb2jPX35g29fCfQ6E',
    appId: '1:1030098231404:web:79d473fd47e7a5e7dbb849',
    messagingSenderId: '1030098231404',
    projectId: 'shopv2-d56e6',
    authDomain: 'shopv2-d56e6.firebaseapp.com',
    storageBucket: 'shopv2-d56e6.appspot.com',
    measurementId: 'G-XEKS9CG6RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZD4ZVs7-1Snf_kd4iPRXWXwMjuNtEdSk',
    appId: '1:1030098231404:android:5c6f64dd567430eddbb849',
    messagingSenderId: '1030098231404',
    projectId: 'shopv2-d56e6',
    storageBucket: 'shopv2-d56e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1fm0sORUApWQvgWCK6sQb1DmHkQQyZqQ',
    appId: '1:1030098231404:ios:359995237df8f805dbb849',
    messagingSenderId: '1030098231404',
    projectId: 'shopv2-d56e6',
    storageBucket: 'shopv2-d56e6.appspot.com',
    iosBundleId: 'com.example.shopv2',
  );
}
